// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jsruasujjbrwdggxkfsw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpzcnVhc3VqamJyd2RnZ3hrZnN3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA0NjUwNzUsImV4cCI6MjA3NjA0MTA3NX0.H2QBeKHHu57_rYbkAyEtuaT4NQLoI3VmnRwVLBrkHDE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});